service: aws-python-telegram-bot

provider:
  name: aws
  runtime: python3.8
  stage: dev

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements

package:
  exclude:
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
